# Read the Docs configuration file for Sphinx projects
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    install:
      # Since the install step is overridden, pip is no longer updated automatically.
      - pip install --upgrade pip
      - pip install .
      - pip install --group docs

sphinx:
  configuration: docs/source/conf.py
  # Fail on all warnings to avoid broken references
  fail_on_warning: true

formats:
  - pdf
  - epub


